import type { jsPDF } from "jspdf";

import type { CruiseGuidePdfConfig, Rgb } from "@/lib/pdf/cruise-guide-pdf-config";
import type { PdfFontSupport } from "@/lib/pdf/pdf-text";
import { pdfSafeText, setPdfFont } from "@/lib/pdf/pdf-text";
import type { PortRecommendation } from "@/lib/norway-cruise-planner-engine";
import type { PdfHeroImage } from "@/lib/pdf/cruise-guide-pdf-schedule";

export type PdfContext = {
  pdf: jsPDF;
  config: CruiseGuidePdfConfig;
  fonts: PdfFontSupport;
  margin: number;
  footerReserve: number;
  pageWidth: number;
  pageHeight: number;
  contentWidth: number;
  y: number;
};

export function pdfSetFont(
  ctx: PdfContext,
  style: "normal" | "bold" = "normal",
): void {
  setPdfFont(ctx.pdf, style, ctx.fonts);
}

export function createPdfContext(
  pdf: jsPDF,
  config: CruiseGuidePdfConfig,
  fonts: PdfFontSupport,
): PdfContext {
  const margin = 14;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  return {
    pdf,
    config,
    fonts,
    margin,
    footerReserve: 16,
    pageWidth,
    pageHeight,
    contentWidth: pageWidth - margin * 2,
    y: margin,
  };
}

export function setFillRgb(pdf: jsPDF, rgb: Rgb): void {
  pdf.setFillColor(rgb[0], rgb[1], rgb[2]);
}

export function setDrawRgb(pdf: jsPDF, rgb: Rgb): void {
  pdf.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

export function setTextRgb(pdf: jsPDF, rgb: Rgb): void {
  pdf.setTextColor(rgb[0], rgb[1], rgb[2]);
}

export function startNewPage(ctx: PdfContext): void {
  ctx.pdf.addPage();
  ctx.y = ctx.margin;
}

export function ensureSpace(ctx: PdfContext, height: number): void {
  if (ctx.y + height > ctx.pageHeight - ctx.footerReserve) {
    startNewPage(ctx);
  }
}

export function drawDivider(ctx: PdfContext, y: number): void {
  setDrawRgb(ctx.pdf, ctx.config.colors.gold);
  ctx.pdf.setLineWidth(0.3);
  ctx.pdf.line(ctx.margin, y, ctx.pageWidth - ctx.margin, y);
}

export function drawBrandedHeader(
  ctx: PdfContext,
  subtitle?: string,
): number {
  const { pdf, config, margin, pageWidth } = ctx;
  const headerHeight = subtitle ? 24 : 20;

  setFillRgb(pdf, config.colors.navyDeep);
  pdf.rect(0, ctx.y, pageWidth, headerHeight, "F");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(11);
  setTextRgb(pdf, config.colors.white);
  pdf.text(config.siteName, margin, ctx.y + 8);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(7.5);
  setTextRgb(pdf, config.colors.gold);
  pdf.text(`Generated by ${config.domain}`, margin, ctx.y + 13.5);

  if (subtitle) {
    pdf.setFontSize(7.5);
    setTextRgb(pdf, config.colors.white);
    pdf.text(subtitle, margin, ctx.y + 19);
  }

  ctx.y += headerHeight + 6;
  return headerHeight;
}

export function drawHeroBanner(
  ctx: PdfContext,
  heroImage: PdfHeroImage | null | undefined,
): number {
  const { pdf, config, pageWidth } = ctx;
  const height = 32;
  const y = ctx.y;

  if (heroImage) {
    pdf.addImage(heroImage.data, heroImage.format, 0, y, pageWidth, height);
  } else {
    setFillRgb(pdf, config.colors.navyDeep);
    pdf.rect(0, y, pageWidth, height * 0.65, "F");
    setFillRgb(pdf, config.colors.fjordBlue);
    pdf.rect(0, y + height * 0.45, pageWidth, height * 0.55, "F");
  }

  setFillRgb(pdf, config.colors.navyDeep);
  pdf.rect(0, y + height - 12, pageWidth, 12, "F");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(9);
  setTextRgb(pdf, config.colors.white);
  pdf.text(config.destinationName, ctx.margin, y + height - 4);

  ctx.y = y + height + 8;
  return height;
}

export function drawCountdownBox(ctx: PdfContext, daysUntil: number): void {
  const { pdf, config, margin, contentWidth } = ctx;
  const height = 18;

  ensureSpace(ctx, height + 4);

  setFillRgb(pdf, config.colors.softGrey);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(margin, ctx.y, contentWidth, height, 2, 2, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7.5);
  setTextRgb(pdf, config.colors.slate);
  pdf.text("YOUR CRUISE DEPARTS IN", margin + 4, ctx.y + 6);

  pdf.setFontSize(16);
  setTextRgb(pdf, config.colors.navyDeep);
  const dayLabel = daysUntil === 1 ? "1 Day" : `${daysUntil} Days`;
  pdf.text(dayLabel, margin + 4, ctx.y + 14);

  ctx.y += height + 6;
}

export function drawPageFooter(
  ctx: PdfContext,
  pageNumber: number,
  totalPages: number,
): void {
  const { pdf, config, margin, pageWidth, pageHeight } = ctx;
  const footerY = pageHeight - 10;

  drawDivider(ctx, footerY - 4);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(7.5);
  setTextRgb(pdf, config.colors.slate);
  pdf.text(config.footerText, margin, footerY);

  const pageLabel = `Page ${pageNumber} of ${totalPages}`;
  pdf.text(pageLabel, pageWidth - margin - pdf.getTextWidth(pageLabel), footerY);
}

export function drawSummaryCard(
  ctx: PdfContext,
  x: number,
  y: number,
  width: number,
  height: number,
  label: string,
  value: string,
  detail?: string,
): void {
  const { pdf, config } = ctx;

  setFillRgb(pdf, config.colors.white);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(x, y, width, height, 2, 2, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7);
  setTextRgb(pdf, config.colors.slate);
  pdf.text(label.toUpperCase(), x + 3, y + 5);

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(10);
  setTextRgb(pdf, config.colors.navyDeep);
  const valueLines = pdf.splitTextToSize(value, width - 6);
  pdf.text(valueLines.slice(0, 2), x + 3, y + 11);

  if (detail) {
    pdfSetFont(ctx, "normal");
    pdf.setFontSize(7);
    setTextRgb(pdf, config.colors.slate);
    const detailLines = pdf.splitTextToSize(detail, width - 6);
    pdf.text(detailLines.slice(0, 2), x + 3, y + height - 5);
  }
}

export function drawPremiumScoreCard(
  ctx: PdfContext,
  score: number,
  bandLabel: string,
  starLine: string,
  fitnessLevel: string,
): number {
  const { pdf, config, margin, contentWidth } = ctx;
  const cardHeight = 34;

  ensureSpace(ctx, cardHeight + 4);

  setFillRgb(pdf, config.colors.navyDeep);
  pdf.roundedRect(margin, ctx.y, contentWidth, cardHeight, 3, 3, "F");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7);
  setTextRgb(pdf, config.colors.gold);
  pdf.text("CRUISE MATCH SCORE", margin + 4, ctx.y + 6);

  pdf.setFontSize(22);
  setTextRgb(pdf, config.colors.white);
  pdf.text(String(score), margin + 4, ctx.y + 16);
  pdf.setFontSize(9);
  pdf.text("/100", margin + 18, ctx.y + 16);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(8.5);
  pdf.text(starLine, margin + 32, ctx.y + 16);

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(9);
  pdf.text(bandLabel, margin + 4, ctx.y + 23);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(7.5);
  setTextRgb(pdf, config.colors.softGrey);
  pdf.text(
    `Personalised to your cruise interests and ${fitnessLevel.toLowerCase()} fitness level`,
    margin + 4,
    ctx.y + 29,
  );

  const used = cardHeight + 4;
  ctx.y += used;
  return used;
}

export function drawReturnConfidenceCard(
  ctx: PdfContext,
  starLine: string,
  label: string,
  detail: string,
): number {
  const { pdf, config, margin, contentWidth } = ctx;
  const cardHeight = 34;

  ensureSpace(ctx, cardHeight + 4);

  setFillRgb(pdf, config.colors.cardBg);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(margin, ctx.y, contentWidth, cardHeight, 3, 3, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7);
  setTextRgb(pdf, config.colors.slate);
  pdf.text("RETURN-TO-SHIP CONFIDENCE", margin + 4, ctx.y + 6);

  pdf.setFontSize(9);
  setTextRgb(pdf, config.colors.navyDeep);
  pdf.text(`${starLine} ${label}`, margin + 4, ctx.y + 13);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(7.5);
  setTextRgb(pdf, config.colors.slate);
  const detailLines = pdf.splitTextToSize(detail, contentWidth - 8);
  pdf.text(detailLines.slice(0, 2), margin + 4, ctx.y + 19);

  const used = cardHeight + 4;
  ctx.y += used;
  return used;
}

export function drawCtaButton(
  ctx: PdfContext,
  x: number,
  y: number,
  width: number,
  label: string,
  url: string,
  variant: "primary" | "navy" = "primary",
): number {
  const { pdf, config } = ctx;
  const height = 9;
  const fill = variant === "primary" ? config.colors.fjordBlue : config.colors.navyDeep;

  setFillRgb(pdf, fill);
  pdf.roundedRect(x, y, width, height, 2, 2, "F");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(8.5);
  setTextRgb(pdf, config.colors.white);
  const safeLabel = pdfSafeText(label, ctx.fonts);
  const textWidth = pdf.getTextWidth(safeLabel);
  pdf.text(safeLabel, x + (width - textWidth) / 2, y + 6);

  pdf.link(x, y, width, height, { url });

  return height;
}

export function drawSectionPanel(
  ctx: PdfContext,
  title: string,
  bodyLines: readonly string[],
): void {
  const { pdf, config, margin, contentWidth } = ctx;
  const pad = 4;
  const innerX = margin + pad;
  const innerWidth = contentWidth - pad * 2;
  const top = ctx.y;

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(8);
  const wrappedLines = bodyLines.flatMap((line) =>
    pdf.splitTextToSize(line, innerWidth),
  );
  const boxHeight = 10 + wrappedLines.length * 3.6 + pad;

  ensureSpace(ctx, boxHeight + 4);

  setFillRgb(pdf, config.colors.cardBg);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(margin, top, contentWidth, boxHeight, 2, 2, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(9.5);
  setTextRgb(pdf, config.colors.navyDeep);
  pdf.text(title, innerX, top + 6);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(8);
  setTextRgb(pdf, config.colors.slate);

  let lineY = top + 11;
  for (const line of wrappedLines) {
    pdf.text(line, innerX, lineY);
    lineY += 3.6;
  }

  ctx.y = top + boxHeight + 4;
}

export function writeWrappedText(
  ctx: PdfContext,
  text: string,
  x: number,
  maxWidth: number,
  lineHeight: number,
  fontSize: number,
  color: Rgb,
  font: "normal" | "bold" = "normal",
): number {
  const { pdf } = ctx;
  pdfSetFont(ctx, font === "bold" ? "bold" : "normal");
  pdf.setFontSize(fontSize);
  setTextRgb(pdf, color);
  const lines = pdf.splitTextToSize(text, maxWidth);
  ensureSpace(ctx, lines.length * lineHeight);
  pdf.text(lines, x, ctx.y);
  const used = lines.length * lineHeight;
  ctx.y += used;
  return used;
}

export function shortenText(text: string, maxLength = 130): string {
  const trimmed = text.trim();
  if (trimmed.length <= maxLength) return trimmed;

  const sentence = trimmed.split(/(?<=[.!?])\s+/)[0]?.trim() ?? trimmed;
  if (sentence.length <= maxLength) return sentence;

  return `${trimmed.slice(0, maxLength - 3).trim()}...`;
}

export function resolvePortBookingUrl(
  rec: PortRecommendation,
  config: CruiseGuidePdfConfig,
): string {
  for (const pattern of config.tourBookingPatterns) {
    if (pattern.match.test(rec.recommended)) {
      return pattern.url;
    }
  }

  const portUrl = config.portBookingUrls[rec.portSlug];
  if (portUrl) return portUrl;

  return config.urls.defaultBooking;
}

export function buildVoyageSubtitle(
  cruiseLine: string,
  shipName: string,
  sailingMonth: string,
  sailingYear = "2026",
): string {
  const parts = [
    shipName.trim() || undefined,
    cruiseLine.trim() || undefined,
    sailingMonth.trim()
      ? `${sailingMonth.trim()} / ${sailingYear}`
      : sailingYear,
  ].filter(Boolean);

  return parts.join(" · ");
}

export function drawBulletList(
  ctx: PdfContext,
  x: number,
  maxWidth: number,
  bullets: readonly string[],
): number {
  const { pdf, config } = ctx;
  let used = 0;

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(8);
  setTextRgb(pdf, config.colors.slate);

  for (const bullet of bullets) {
    ensureSpace(ctx, 4);
    const lines = pdf.splitTextToSize(`• ${bullet}`, maxWidth);
    pdf.text(lines, x, ctx.y);
    used += lines.length * 3.6;
    ctx.y += lines.length * 3.6;
  }

  return used;
}

export function drawBodyText(
  ctx: PdfContext,
  x: number,
  maxWidth: number,
  body: string,
): number {
  const { pdf, config } = ctx;
  pdfSetFont(ctx, "normal");
  pdf.setFontSize(8);
  setTextRgb(pdf, config.colors.slate);
  const lines = pdf.splitTextToSize(body, maxWidth);
  ensureSpace(ctx, lines.length * 3.6);
  pdf.text(lines, x, ctx.y);
  const used = lines.length * 3.6;
  ctx.y += used;
  return used;
}

export function drawLabelValueLine(
  ctx: PdfContext,
  x: number,
  y: number,
  label: string,
  value: string,
  maxWidth: number,
  labelWidth = 28,
): void {
  const { pdf, config } = ctx;

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(6.8);
  setTextRgb(pdf, config.colors.navyDeep);
  pdf.text(`${label}:`, x, y);

  pdfSetFont(ctx, "normal");
  setTextRgb(pdf, config.colors.slate);
  const valueLines = pdf.splitTextToSize(value, maxWidth - labelWidth);
  pdf.text(valueLines[0] ?? value, x + labelWidth, y);
}

export type ShipSchedulePanelInput = {
  arrivalLabel: string;
  allAboardLabel: string | null;
  portTimeLabel: string | null;
  durationLabel: string;
  marginLabel: string | null;
  confidenceLabel: string | null;
  confirmAllAboardMessage?: string;
};

export function drawMatchScoreSideCard(
  ctx: PdfContext,
  x: number,
  y: number,
  width: number,
  score: number,
  bandLabel: string,
  starRating: number,
  fitnessLevel: string,
): number {
  const { pdf, config } = ctx;
  const height = 36;

  setFillRgb(pdf, config.colors.navyDeep);
  pdf.roundedRect(x, y, width, height, 3, 3, "F");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7);
  setTextRgb(pdf, config.colors.gold);
  pdf.text("CRUISE MATCH SCORE", x + 4, y + 6);

  pdf.setFontSize(18);
  setTextRgb(pdf, config.colors.white);
  pdf.text(`${score}/100`, x + 4, y + 15);

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(9);
  pdf.text(bandLabel, x + 4, y + 22);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(7.5);
  setTextRgb(pdf, config.colors.softGrey);
  pdf.text(`Rating: ${starRating}/5`, x + 4, y + 27);
  pdf.text(
    `Personalised to your cruise interests and ${fitnessLevel.toLowerCase()} fitness level`,
    x + 4,
    y + 32,
  );

  return height;
}

export function drawReturnConfidenceSideCard(
  ctx: PdfContext,
  x: number,
  y: number,
  width: number,
  headline: string,
  ratingLine: string,
  detail: string,
): number {
  const { pdf, config } = ctx;
  const height = 36;

  setFillRgb(pdf, config.colors.cardBg);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(x, y, width, height, 3, 3, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7);
  setTextRgb(pdf, config.colors.slate);
  pdf.text("RETURN-TO-SHIP CONFIDENCE", x + 4, y + 6);

  pdf.setFontSize(9.5);
  setTextRgb(pdf, config.colors.navyDeep);
  pdf.text(headline, x + 4, y + 13);

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(8);
  pdf.text(ratingLine, x + 4, y + 18.5);

  pdfSetFont(ctx, "normal");
  pdf.setFontSize(6.8);
  setTextRgb(pdf, config.colors.slate);
  const detailLines = pdf.splitTextToSize(detail, width - 8);
  pdf.text(detailLines.slice(0, 2), x + 4, y + 23.5);

  return height;
}

export type YourCruisePanelInput = {
  shipName: string;
  arrivalLabel: string;
  departureLabel: string;
  portTimeLabel: string | null;
};

export function drawYourCruisePanel(
  ctx: PdfContext,
  input: YourCruisePanelInput,
): number {
  const { pdf, config, margin, contentWidth } = ctx;
  const height = 24;
  const y = ctx.y;

  ensureSpace(ctx, height + 4);

  setFillRgb(pdf, config.colors.softGrey);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(margin, y, contentWidth, height, 2, 2, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(7);
  setTextRgb(pdf, config.colors.slate);
  pdf.text("YOUR CRUISE", margin + 4, y + 5);

  drawLabelValueLine(ctx, margin + 4, y + 9.5, "Ship", input.shipName, contentWidth / 2 - 8, 12);
  drawLabelValueLine(
    ctx,
    margin + contentWidth / 2,
    y + 9.5,
    "Arrival",
    input.arrivalLabel,
    contentWidth / 2 - 8,
    14,
  );
  drawLabelValueLine(
    ctx,
    margin + 4,
    y + 14,
    "Departure",
    input.departureLabel,
    contentWidth / 2 - 8,
    18,
  );

  if (input.portTimeLabel) {
    drawLabelValueLine(
      ctx,
      margin + contentWidth / 2,
      y + 14,
      "Port Time",
      input.portTimeLabel,
      contentWidth / 2 - 8,
      14,
    );
  }

  ctx.y = y + height + 4;
  return height + 4;
}

export type CruiseFitSummaryPanelInput = {
  portTimeLabel: string;
  excursionDurationLabel: string;
  returnMarginLabel: string;
  confidenceStars: number;
  confidenceLabel: string;
};

export function drawCruiseFitSummaryPanel(
  ctx: PdfContext,
  x: number,
  y: number,
  width: number,
  input: CruiseFitSummaryPanelInput,
): number {
  const { pdf, config } = ctx;
  const height = 24;

  setFillRgb(pdf, config.colors.softGrey);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.15);
  pdf.roundedRect(x, y, width, height, 1.5, 1.5, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(6.8);
  setTextRgb(pdf, config.colors.navyDeep);
  pdf.text("Cruise Fit Summary", x + 3, y + 4.5);

  drawLabelValueLine(ctx, x + 3, y + 8.5, "Port Time", input.portTimeLabel, width / 2 - 6, 16);
  drawLabelValueLine(
    ctx,
    x + width / 2,
    y + 8.5,
    "Excursion Duration",
    input.excursionDurationLabel,
    width / 2 - 6,
    28,
  );
  drawLabelValueLine(
    ctx,
    x + 3,
    y + 12.5,
    "Return Margin",
    input.returnMarginLabel,
    width / 2 - 6,
    22,
  );
  drawLabelValueLine(
    ctx,
    x + width / 2,
    y + 12.5,
    "Confidence",
    `${input.confidenceStars}/5 ${input.confidenceLabel}`,
    width / 2 - 6,
    18,
  );

  return height;
}

export function drawShipSchedulePanel(
  ctx: PdfContext,
  x: number,
  y: number,
  width: number,
  input: ShipSchedulePanelInput,
): number {
  const { pdf, config } = ctx;
  const hasFitDetails =
    input.allAboardLabel &&
    input.portTimeLabel &&
    input.marginLabel &&
    input.confidenceLabel;
  const height = hasFitDetails ? 22 : 12;

  setFillRgb(pdf, config.colors.softGrey);
  setDrawRgb(pdf, config.colors.border);
  pdf.setLineWidth(0.15);
  pdf.roundedRect(x, y, width, height, 1.5, 1.5, "FD");

  pdfSetFont(ctx, "bold");
  pdf.setFontSize(6.5);
  setTextRgb(pdf, config.colors.navyDeep);
  pdf.text("Your Ship in Port", x + 3, y + 4);

  drawLabelValueLine(ctx, x + 3, y + 7.5, "Arrives", input.arrivalLabel, width / 2 - 6, 14);

  if (input.allAboardLabel) {
    drawLabelValueLine(
      ctx,
      x + width / 2,
      y + 7.5,
      "All Aboard",
      input.allAboardLabel,
      width / 2 - 6,
      18,
    );
  }

  if (hasFitDetails) {
    drawLabelValueLine(ctx, x + 3, y + 11, "Port Time", input.portTimeLabel!, width - 6, 16);

    pdfSetFont(ctx, "bold");
    pdf.setFontSize(6.5);
    setTextRgb(pdf, config.colors.navyDeep);
    pdf.text("Recommended Excursion", x + 3, y + 14.5);

    drawLabelValueLine(ctx, x + 3, y + 18, "Duration", input.durationLabel, width / 2 - 6, 16);
    drawLabelValueLine(
      ctx,
      x + width / 2,
      y + 18,
      "Return Margin",
      input.marginLabel!,
      width / 2 - 6,
      22,
    );
    drawLabelValueLine(
      ctx,
      x + 3,
      y + 21,
      "Confidence",
      input.confidenceLabel!,
      width - 6,
      18,
    );
  } else if (input.confirmAllAboardMessage) {
    pdfSetFont(ctx, "normal");
    pdf.setFontSize(6.3);
    setTextRgb(pdf, config.colors.slate);
    const lines = pdf.splitTextToSize(input.confirmAllAboardMessage, width - 6);
    pdf.text(lines.slice(0, 1), x + 3, y + 10.5);
  }

  return height;
}
