import { siteImages } from "@/lib/site-images";

export type Rgb = readonly [number, number, number];

export type TravelGuideSection = {
  title: string;
  bullets?: readonly string[];
  body?: string;
};

/**
 * Reusable brand config for Norway and future destination PDF guides
 * (Caribbean, Alaska, Mediterranean, Canada). Swap values per market.
 */
const SHARED_BRAND_COLOURS = {
  navy: "#0A2540",
  navyDeep: "#061A2E",
  fjordBlue: "#4DB8D9",
  softGrey: "#F1F5F9",
  white: "#FFFFFF",
  gold: "#C9A227",
  green: "#2D6A4F",
  slate: "#475569",
  cardBg: "#F8FAFC",
  border: "#E2E8F0",
} as const;

export const brandConfig = {
  siteName: "Norway Shore Excursions",
  domain: "norwayshoreexcursions.com",
  baseUrl: "https://norwayshoreexcursions.com",
  destinationName: "Norway",
  brandColours: SHARED_BRAND_COLOURS,
  colours: SHARED_BRAND_COLOURS,
  defaultHeroImage: siteImages.hero,
  defaultBookingUrl: "https://norwayshoreexcursions.com/excursions",
  footerText:
    "Generated by Norway Shore Excursions · Confirm all aboard times with your cruise operator",
} as const;

function hexToRgb(hex: string): Rgb {
  const normalized = hex.replace("#", "");
  const value = Number.parseInt(normalized, 16);
  return [(value >> 16) & 255, (value >> 8) & 255, value & 255];
}

export type CruiseGuidePdfConfig = {
  siteName: string;
  domain: string;
  destinationName: string;
  guideTitle: string;
  defaultHeroImage: string;
  colors: {
    navy: Rgb;
    navyDeep: Rgb;
    fjordBlue: Rgb;
    softGrey: Rgb;
    white: Rgb;
    gold: Rgb;
    green: Rgb;
    slate: Rgb;
    cardBg: Rgb;
    border: Rgb;
  };
  urls: {
    home: string;
    excursions: string;
    defaultBooking: string;
  };
  footerText: string;
  travelGuidePageTitle: string;
  travelGuideSections: readonly TravelGuideSection[];
  whyBookSection: {
    title: string;
    bullets: readonly string[];
  };
  portBookingUrls: Readonly<Record<string, string>>;
  tourBookingPatterns: ReadonlyArray<{
    match: RegExp;
    url: string;
  }>;
};

export const defaultNorwayCruiseGuidePdfConfig: CruiseGuidePdfConfig = {
  siteName: brandConfig.siteName,
  domain: brandConfig.domain,
  destinationName: brandConfig.destinationName,
  guideTitle: `Your Personal ${brandConfig.destinationName} Cruise Guide`,
  defaultHeroImage: brandConfig.defaultHeroImage,
  colors: {
    navy: hexToRgb(brandConfig.colours.navy),
    navyDeep: hexToRgb(brandConfig.colours.navyDeep),
    fjordBlue: hexToRgb(brandConfig.colours.fjordBlue),
    softGrey: hexToRgb(brandConfig.colours.softGrey),
    white: hexToRgb(brandConfig.colours.white),
    gold: hexToRgb(brandConfig.colours.gold),
    green: hexToRgb(brandConfig.colours.green),
    slate: hexToRgb(brandConfig.colours.slate),
    cardBg: hexToRgb(brandConfig.colours.cardBg),
    border: hexToRgb(brandConfig.colours.border),
  },
  urls: {
    home: brandConfig.baseUrl,
    excursions: brandConfig.defaultBookingUrl,
    defaultBooking: brandConfig.defaultBookingUrl,
  },
  footerText: brandConfig.footerText,
  travelGuidePageTitle: `Before You Sail: ${brandConfig.destinationName} Cruise Tips`,
  travelGuideSections: [
    {
      title: "What to Pack",
      bullets: [
        "Waterproof jacket",
        "Comfortable walking shoes",
        "Layers",
        "Sunglasses for bright fjord days",
        "Small day bag",
      ],
    },
    {
      title: "Norway Weather",
      body:
        "Fjord weather can change quickly, even on sunny sailing days. Dress in layers, keep a light rain shell handy, and plan for cooler breezes on deck and at viewpoints.",
    },
    {
      title: "Money & Payments",
      body:
        "Card payments are widely accepted across Norway, but a small backup of local currency can still be useful for snacks, taxis, or smaller rural stops.",
    },
    {
      title: "Cruise Passenger Tips",
      bullets: [
        "Check your ship's all aboard time",
        "Choose excursions that match your fitness level",
        "Allow buffer time before returning to the ship",
        "Book popular fjord and glacier trips early",
      ],
    },
  ],
  whyBookSection: {
    title: "Why Book With Norway Shore Excursions",
    bullets: [
      "Cruise focused excursion planning",
      "Small group and scenic tour options",
      "Clear return to ship thinking",
      "Destination specific advice",
    ],
  },
  portBookingUrls: {
    flam: "https://norwayshoreexcursions.com/stegastein-viewpoint-shore-excursion",
    bergen: "https://norwayshoreexcursions.com/bergen-shore-excursions",
    nordfjordeid: "https://norwayshoreexcursions.com/excursions",
    olden: "https://norwayshoreexcursions.com/excursions",
    geiranger: "https://norwayshoreexcursions.com/excursions",
    stavanger: "https://norwayshoreexcursions.com/excursions",
  },
  tourBookingPatterns: [
    {
      match: /stegastein/i,
      url: "https://norwayshoreexcursions.com/stegastein-viewpoint-shore-excursion",
    },
    {
      match: /mostraumen/i,
      url: "https://norwayshoreexcursions.com/bergen-shore-excursions",
    },
    {
      match: /briksdal/i,
      url: "https://norwayshoreexcursions.com/excursions",
    },
  ],
};
